# Análisis de resultados — suite de evaluación

Lee el CSV más reciente generado por `src.evals.run` (modo full, 30 partidos) y produce:

1. Métricas agregadas sobre los 30 partidos.
2. Breakdown por tier (top / mid / bottom).
3. Mejores y peores casos por cada métrica.
4. Distribución de formaciones propuestas vs reales.
5. Errores si los hay.

Este notebook va a ser la base del análisis de resultados de Miguel y Daniel para la documentación.

In [1]:
import glob
import json
from pathlib import Path

import pandas as pd

for candidate in [Path('evals/results'), Path('../evals/results')]:
    if candidate.exists():
        RESULTS = candidate.resolve()
        break

full_runs = sorted(glob.glob(str(RESULTS / 'results_full_*.csv')))
if not full_runs:
    raise FileNotFoundError('No hay results_full_*.csv. Corre src.evals.run primero.')
latest = full_runs[-1]
df = pd.read_csv(latest)
print(f'Archivo: {Path(latest).name}')
print(f'Partidos evaluados: {len(df)}')
print(f'Columnas: {len(df.columns)}')

Archivo: results_full_20260528_103048.csv
Partidos evaluados: 30
Columnas: 21

## 1. Métricas agregadas

In [2]:
METRIC_COLS = ['lineup_overlap', 'formation_match', 'tactical_coherence', 'specificity', 'faithfulness']
df[METRIC_COLS].describe().round(2)

,lineup_overlap,formation_match,tactical_coherence,specificity,faithfulness
count,30.00,30.00,30.00,30.0,30.00
mean,0.58,0.37,3.83,4.1,3.17
std,0.18,0.49,0.59,0.4,0.83
min,0.27,0.00,3.00,3.0,2.00
25%,0.39,0.00,3.25,4.0,3.00
50%,0.64,0.00,4.00,4.0,3.00
75%,0.70,1.00,4.00,4.0,4.00
max,0.91,1.00,5.00,5.0,5.00

## 2. Breakdown por tier

¿El sistema rinde igual para equipos top, mid y bottom?

In [3]:
df.groupby('tier')[METRIC_COLS].mean().round(2).reindex(['top', 'mid', 'bottom'])

,lineup_overlap,formation_match,tactical_coherence,specificity,faithfulness
tier,,,,,
top,0.44,0.5,3.8,3.9,3.3
mid,0.65,0.5,3.9,4.1,2.9
bottom,0.64,0.1,3.8,4.3,3.3

In [4]:
df.groupby('tier')[METRIC_COLS].std().round(2).reindex(['top', 'mid', 'bottom'])

,lineup_overlap,formation_match,tactical_coherence,specificity,faithfulness
tier,,,,,
top,0.14,0.53,0.63,0.32,0.82
mid,0.13,0.53,0.74,0.32,0.88
bottom,0.19,0.32,0.42,0.48,0.82

## 3. Mejores y peores casos

Para entender qué falla y qué funciona, vemos los 3 partidos con mejor y peor puntaje en cada dimensión.

In [5]:
cols = ['tier', 'our_team', 'opponent', 'faithfulness', 'faithfulness_why']
print('=== Mejor faithfulness ===')
df.nlargest(3, 'faithfulness')[cols].to_string(index=False)

=== Mejor faithfulness ===

'tier    our_team   opponent  faithfulness                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             faithfulness_why\n top Real Madrid Celta Vigo             5                                                                                                                                                                                Todos los datos citados en el plan (PPDA 14.51, xG en contra 56.3, 48 goles encajados, 263 deep completions) están presentes y son exactos respecto al scouting validado. No se inventa ningún número ni se atribuyen características al Celta que no figuren en el informe; el plan es una traducción directa y fiel del análisis del rival.\n mid    Espanyol  Barcelona             5                                                                                  Todas las afirmaciones tácticas del plan tienen respaldo directo en el scouting: la vulnerabilidad en transiciones rápidas está documentada con las derrotas ante Alavés y Valencia, las deep completions (438) justifican el repliegue compacto para cerrar el centro, y la presión a los laterales responde explícitamente a la recomendación del scouting. El plan no inventa estadísticas ni cita datos que no aparezcan en el informe.\n top   Barcelona    Sevilla             4 La mayoría de los datos citados son consistentes con el scouting: PPDA 9.62 del Sevilla, 61.3 xG en contra y la vulnerabilidad en transición están directamente respaldados. Sin embargo, las estadísticas individuales de jugadores del Barcelona (xG de Yamal 14.66, Lewandowski 14 goles, Olmo 8.75 xG, PPDA propio 7.31, minutos de Bernal 798) no aparecen en el scouting proporcionado y no pueden verificarse con los datos disponibles, lo que introduce un riesgo de cifras no respaldadas por la fuente entregada.'

In [6]:
print('=== Peor faithfulness ===')
df.nsmallest(3, 'faithfulness')[cols].to_string(index=False)

=== Peor faithfulness ===

"tier       our_team        opponent  faithfulness                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     faithfulness_why\n top     Celta Vigo Atletico Madrid             2                                                                              El plan cita correctamente el PPDA (11.68), los xG del partido Celta-Atlético (0.29 vs 2.79) y las deep completions (351), todos presentes en el scouting. Sin embargo, introduce datos no respaldados por el scouting: los 14 goles y 11.61 xG de Borja Iglesias, los 9 goles y 6.6 xG de Ferran Jutglà (que además no está en el XI), las asistencias y xA de Rueda, Carreira, Moriba y Aspas, y los 1544 minutos de Beltrán. Ninguna de estas cifras aparece en el scouting proporcionado, lo que constituye una fabricación significativa de datos.\n mid         Getafe     Real Oviedo             2                                                                      Los datos del rival (PPDA 13.69, 147 deep completions, 67.7 xG en contra, 26 goles marcados, racha de 0 goles en 5 partidos) están correctamente extraídos del scouting. Sin embargo, las estadísticas individuales de jugadores propios —Milla '10 asistencias, 6.84 xA', Arambarri '6 goles, 8.08 xG, 57 shots', Satriano '6 goles, 4.71 xG', Liso '3 goles, 2.76 xG', y el dato de Getafe '48.3 xG concedidos'— no aparecen en ningún momento en el scouting proporcionado y no pueden verificarse, lo que constituye una invención significativa de cifras.\n mid Rayo Vallecano      Villarreal             2 Los datos de Villarreal (PPDA 16.38, 289 deep completions, 72 goles, xG 68.8) están correctamente extraídos del scouting. Sin embargo, el plan introduce cifras de Rayo Vallecano que no aparecen en ningún momento en el scouting proporcionado: xG de Rayo (60.0 vs 56.3), xA de Ratiu (6.19) y Chavarría (3.7), goles/xG individuales de De Frutos (10 goles, 12.13 xG), Álvaro García (4 goles, 6.87 xG), Camello (5 goles en 810 min) y key passes de Gumbau (23 en 1153 min). Todos estos números son inventados o al menos no verificables con la información disponible, lo que supone una falta de fidelidad significativa."

In [7]:
cols2 = ['tier', 'our_team', 'opponent', 'lineup_overlap', 'formation_proposed', 'formation_actual']
print('=== Mejor lineup_overlap ===')
df.nlargest(3, 'lineup_overlap')[cols2].to_string(index=False)

=== Mejor lineup_overlap ===

'  tier our_team    opponent  lineup_overlap formation_proposed formation_actual\nbottom  Osasuna      Alaves           0.909              4-5-1            4-5-1\nbottom Mallorca    Valencia           0.909              4-4-2            4-5-1\n   mid   Getafe Real Oviedo           0.818              5-3-2            5-3-2'

In [8]:
print('=== Peor lineup_overlap ===')
df.nsmallest(3, 'lineup_overlap')[cols2].to_string(index=False)

=== Peor lineup_overlap ===

'  tier        our_team opponent  lineup_overlap formation_proposed formation_actual\n   top Atletico Madrid   Getafe           0.273              4-3-3            4-5-1\nbottom         Sevilla    Elche           0.273              4-3-3            3-4-3\n   top      Celta Vigo  Levante           0.364              3-4-3            3-4-3'

## 4. Formaciones — propuestas vs reales

In [9]:
print('Formaciones más propuestas por el Coach:')
print(df['formation_proposed'].value_counts().to_string())
print()
print('Formaciones reales (detectadas desde ESPN):')
print(df['formation_actual'].value_counts().to_string())

Formaciones más propuestas por el Coach:
formation_proposed
4-3-3      10
4-4-2       7
3-4-3       5
4-5-1       5
4-2-3-1     2
5-3-2       1

Formaciones reales (detectadas desde ESPN):
formation_actual
4-5-1    15
3-4-3     5
4-4-2     5
4-3-3     2
5-3-2     2
3-5-2     1

In [10]:
pd.crosstab(df['formation_actual'], df['formation_proposed'], margins=True, margins_name='Total')

formation_proposed  3-4-3  4-2-3-1  4-3-3  4-4-2  4-5-1  5-3-2  Total
formation_actual
3-4-3                   4        0      1      0      0      0      5
3-5-2                   0        0      1      0      0      0      1
4-3-3                   0        0      1      0      1      0      2
4-4-2                   1        1      1      2      0      0      5
4-5-1                   0        1      6      5      3      0     15
5-3-2                   0        0      0      0      1      1      2
Total                   5        2     10      7      5      1     30

## 5. Errores

In [11]:
errs = df[df['error'].fillna('') != '']
if errs.empty:
    print('Sin errores en los 30 partidos.')
else:
    print(f'{len(errs)} partidos con error:')
    print(errs[['tier', 'our_team', 'opponent', 'error']].to_string(index=False))

Sin errores en los 30 partidos.

## Notas para Miguel y Daniel

- Las métricas estructuradas (`lineup_overlap`, `formation_match`) son objetivas y reproducibles.
- Las métricas del juez (`tactical_coherence`, `specificity`, `faithfulness`) son subjetivas — un modelo (Sonnet 4.6) puntuando otro (Haiku 4.5). Hay que documentar esta limitación.
- `faithfulness` está medida contra el scouting visible al juez, NO contra el ground truth completo (decisión metodológica del v1).
- `lineup_overlap` está sub-medido por desajustes de nombre entre Understat (lo que ve el Coach) y ESPN (el ground truth). Una mejora futura sería fuzzy match con rapidfuzz.